# Paste this in your current configuration.yaml
# If you have other entities, like a button, you have to paste all elements under the "button" parent.
# This is because you can only have 1 parent of each type at the top level (button, lovelace, input_text etc.)

lovelace:
  mode: yaml
  dashboards:
    zentorro-home:
      mode: yaml
      filename: zentorro-home.yaml
      title: Zentorro Home
      icon: mdi:remote
      show_in_sidebar: true

mqtt:
  button:
    - name: "Start learning"
      command_topic: dump
      icon: mdi:play-outline
    - name: "Set state"
      platform: mqtt
      command_topic: dump
      icon: mdi:power
    - name: "Set state"
      platform: mqtt
      command_topic: dump
      icon: mdi:power
    - name: "Clear database"
      platform: mqtt
      command_topic: 433MHzBridge/clear
      icon: mdi:delete-outline
  input_text:
    zentorro_new_device_name:
      name: Device name
      mode: text
      icon: mdi:label-outline
    zentorro_new_device_state:
      name: State
      mode: text
      icon: mdi:toggle-switch-outline
    zentorro_control_device_state:
      name: State
      mode: text
      icon: mdi:toggle-switch-outline
    zentorro_control_device_name:
      name: Device name
      mode: text
      icon: mdi:label-outline
  switch:
    - name: "Learning status"
      command_topic: none
      state_topic: 433MHzBridge/status
      payload_on: "ON"
      payload_off: "OFF"
